/* Replace with your SQL commands */

CREATE TABLE IF NOT EXISTS news (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	sender_id INT UNSIGNED NOT NULL,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	latitude FLOAT NULL,
	longitude FLOAT NULL,
	status TINYINT DEFAULT 0,
	picture VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL,
	FOREIGN KEY fk_sender(sender_id) REFERENCES users(id)
);

ALTER TABLE news MODIFY picture TEXT DEFAULT NULL;